### ISSUE TITLE
Could not load 'burst mode' photos

### ISSUE THREAD

**Issue by markotl88** [larcus94/BRNImagePickerSheet#10]
There is a problem with 'burst mode' photos, if you have those kind of photos in library, app crashes.
It's not a problem for my app currently, I can skip those photos, so I just checking if photo is in burst mode in fetchAssets() method, and don't append them to assets, but that's suggestion if you want to show these. My 'solution':

private func fetchAssets() {
          ......
     let result = PHAsset.fetchAssetsWithMediaType(.Image, options: options)
     result.enumerateObjectsUsingBlock { obj, _, _ in
          if let asset = obj as> PHAsset {
                if(asset.burstIdentifier == nil){
                             self.assets.append(asset)
                }
          }
     }
}

**Comment by larcus94** [comment]
@markotl88 Thanks for pointing this out. Fixed this in the last tag. It's a bug in `PHImageManager` that doesn't return an image when the asset represents a burst image. Requesting the image _data_ works though.
