### ISSUE TITLE
building with Carthage

### ISSUE THREAD

**Issue by vinnyt** [larcus94/BRNImagePickerSheet#11]
I am trying to use carthage to get this into a project.  It fails to build with the following:
```
=== BUILD TARGET BRNImagePickerSheet OF PROJECT BRNImagePickerSheet WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “XXXXXXXXXX” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.2'
```

I just started giving carthage a go so it could be something I am doing wrong.  Any thoughts?

**Comment by larcus94** [comment]
I just tried it. It works fine for me. This [issue](https://github.com/Carthage/Carthage/issues/235) might help you out a little.
