### ISSUE TITLE
Resizing edited images

### ISSUE THREAD

**Issue by markotl88** [larcus94/BRNImagePickerSheet#12]
I'm not sure what's the problem (maybe it's my app, but you can check that if you want :), after editing image in iphone library I can't get original size of the image (if I choose it from image picker). But if I choose edited image from Photo Library everything is fine. I took some screenshots from my app, Second photo is original photo picked from picker, fourth photo is edited (picked from picker, too), and fifth is same edited photo picked from Photo Library -> Camera Roll.

![01](https://cloud.githubusercontent.com/assets/10500753/6870342/c01acfd6-d49b-11e4-8a8a-9d1e3ab003ba.PNG)

![02](https://cloud.githubusercontent.com/assets/10500753/6870343/c01f3648-d49b-11e4-85d2-f9c0cb4a7c1c.PNG)

![03](https://cloud.githubusercontent.com/assets/10500753/6870344/c01fd04e-d49b-11e4-9fcd-edb58756ad83.PNG)

![04](https://cloud.githubusercontent.com/assets/10500753/6870345/c020346c-d49b-11e4-9002-768c40d51152.PNG)

![05](https://cloud.githubusercontent.com/assets/10500753/6870341/c00fe012-d49b-11e4-8e0f-ccd58404ffe1.PNG)

**Comment by larcus94** [comment]
Fixed this in 208ce938c46650dd866804a8161a69cc44797c29, thanks for pointing it out :)
