### ISSUE TITLE
Obj-C

### ISSUE THREAD

**Issue by mythodeia** [larcus94/BRNImagePickerSheet#6]
Hello and thanks for this lib. :)
Is there any change this can be ported to Obj-C?

thanks

**Comment by larcus94** [comment]
Well it wouldn't make any sense at all to be honest. It would obviously be possible but I don't get why you'd want to do that?

**Comment by mythodeia** [comment]
I am not yet hands on with Swift and i actively maintain several obj-c projects. If i wanted to make some mods to the library i could do that in Obj-C but not in Swift just yet. Anyway...no worries 
Thanks for your time and of course the library

**Comment by larcus94** [comment]
It shouldn't be too hard to make small changes, even if you're not familiar with Swift :)

**Comment by mythodeia** [comment]
thanks again :+1:

**Comment by larcus94** [comment]
You're very welcome!
