### ISSUE TITLE
Could not obtain unique identifier for attached screen

### ISSUE THREAD

**Issue by korovichev** [larcus94/BRNImagePickerSheet#9]
2015-03-16 01:16:38.893 Example[1186:217454] Could not obtain unique identifier for attached screen <UIScreen: 0x1755fd90; bounds = {{0, 0}, {768, 576}}; mode = <UIScreenMode: 0x17662db0; size = 720.000000 x 576.000000; pixel aspect ratio = 1.092593>>

**Comment by larcus94** [comment]
@korovichev You might want to give me a bit more informations of how I can reproduce this.

**Comment by korovichev** [comment]
Well, I have just downloaded and started the  project in Xcode 6.2 and it didn't started at all, there were some errors, I don't already remember, something about framework that it is not exists. then I fixed that and tried to launch on iPhone 4s and iPad mini 2 retina both with iOS 8.1.3. 

Nothing happened, build succeeded, and I ended up with white screen with no other controls. I tried to modify the start point for the picker to appear, I remove tapRecognizer and made a button, but with no luck (that was made in a separate project). But I had the same error in the original source and in new project. 

Any other details that might help?

**Comment by markotl88** [comment]
You just have to tap on white screen, and ImagePicker is going to show.

**Comment by korovichev** [comment]
Of course I tried to tap. I read the sources to understand what is going on. But nothing happens.

**Comment by larcus94** [comment]
@korovichev The last commit should fix your problem. Reopen the issue if not.
